### ISSUE TITLE
[QUESTION] What JS minifier/combiner are you using?

### ISSUE THREAD

**Issue by TheAlienDrew** [galehouse5/skribbl-io-autodraw#14]
Just want to know for future ease.

**Comment by TheAlienDrew** [comment]
Well basically, what process do you use in order to get the scripts in src to compile into the minified all together bundled versions in dist? I can tell that node/npm is used somewhat, and maybe browserify/tinyify, but other than that, I have no clue.

**Comment by galehouse5** [comment]
Sure thing! I'm using webpack-cli. `webpack --mode=production` to bundle and minify. `webpack --mode=development` to just bundle for local debugging. And I set up my development environment using `npm install --global webpack-cli`.

**Comment by TheAlienDrew** [comment]
Thanks! Though I could only get the webpack to work if i installed color-diff locally, but got it to work
