### ISSUE TITLE
[Question] When it comes to loading images...

### ISSUE THREAD

**Issue by TheAlienDrew** [galehouse5/skribbl-io-autodraw#15]
If it definitely can load the image at least in sources, but for some reason can't draw the image, what would you suspect the problem is?

**Comment by galehouse5** [comment]
Hello @TheAlienDrew. I'd like to investigate this. Are you able to share the image and any instructions I might need in order to reproduce the behavior? Thanks!

**Comment by TheAlienDrew** [comment]
Well, I'm actually making a modified version of your code, to work on another website, so don't think it's anything wrong with your extension.

**Comment by TheAlienDrew** [comment]
But, what I'm having problems with is loading an image, it will load it into the website (you can see it in Sources when debugging view is open in Chrome), yet it says it failed to load/draw the image in the console.

**Comment by galehouse5** [comment]
Hey, @TheAlienDrew. Are you still encountering an issue? If you can include some screenshots that might help me understand what you're explaining.

**Comment by TheAlienDrew** [comment]
I haven't touched my mini project since but it should be a repo on my account.

**Comment by TheAlienDrew** [comment]
Basically I'm trying to reuse the code in a way that it will work on this site. https://github.com/TheAlienDrew/jackbox-tv-tee-ko-autodraw

I basically done all the programming to make it work on the site the only thing I'm having a problem with is it actually getting the images to draw.
