### ISSUE TITLE
Implement google images

### ISSUE THREAD

**Issue by MangaRed** [galehouse5/skribbl-io-autodraw#16]
I've made a simple chrome extension to show google image results of the current word. It could be good if it's implemented in this extension. the advice is instead of drag and drop from another tab, that it shows in the current tab on top of the game a image result set, and by clicking an image it draws directly to canvas
[skribbl helper.zip](https://github.com/galehouse5/skribbl-io-autodraw/files/4289539/skribbl.helper.zip)

**Comment by galehouse5** [comment]
Cool! Thanks for sharing. I do like it.

Let me look into incorporating this kind of functionality when I have time.

**Comment by MangaRed** [comment]
I've developed it. But it was rejected. Check it out
[skribbl helper.zip](https://github.com/galehouse5/skribbl-io-autodraw/files/4303901/skribbl.helper.zip)

It detects when it's your turn and shows automatically the google images. Also plays a sound when it's your turn and the game tab isn't active
