### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by HandsomeMadMario** [galehouse5/skribbl-io-autodraw#17]
i take an image from google, discord, etc., and i drop it on the canvas, and it even says to drop it on to begin drawing but it does nothing when i do. is this fixable in my situation? im on a mac is that helps to explain the issue

**Comment by bmFtZQ** [comment]
I think this is an issue with Chrome for Mac OS because for me it only works when I drop an image from Finder but not from a website.

I think what you can do is drag the image to your desktop then drag it onto the skribbl.io canvas.

**Comment by SungMatt** [comment]
bmFtZQ's fix worked very well for me, you have to download it off the site first before dragging and dropping it into the browser.

**Comment by galehouse5** [comment]
Thanks for the report. 6a990c6 should fix this.

The fix will be published to Chrome Web Store soon.
