### ISSUE TITLE
Just too slow...

### ISSUE THREAD

**Issue by Wyatt-Stanke** [galehouse5/skribbl-io-autodraw#18]
It takes about 150 seconds to finish an image. I know this isn't really an issue, though. I think that it should try to detect the most important part of an image first. Like, the part that has the most colors, or is in the center, or is brighter than everything else.

**Comment by sindreslungaard** [comment]
Try searching for pixel art versions of your word, or pick images with less complexity/color variety.

**Comment by galehouse5** [comment]
Hello, @Wyatt-Stanke.

The number of line draw commands the skribbl.io servers can process is a limiting factor that's out of our control. We can make efficiency improvements that reduce the number of line draw commands needed for a given image. #12 discusses more specifics.

The easiest way to ensure an image draws fast is by deliberately selecting a simple image. You can find this type of image by including the term "clipart" in your Google Images search expression. The worst type of image is a photograph.

![image](https://user-images.githubusercontent.com/1687988/81370419-198e4c80-90c3-11ea-9e15-3422752ce0a2.png)
