### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Filippo780** [galehouse5/skribbl-io-autodraw#20]
IT DOESN'T WORK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by samueld08** [comment]
ikr

**Comment by SungMatt** [comment]
Have you tried [this](https://github.com/galehouse5/skribbl-io-autodraw/issues/17#issuecomment-605659328) fix?

Also, kind reminder: It doesn't quite help to just put "it doesn't work" in a GitHub repo. Try adding some basic information like the OS you're working with, and the browser you're working with. Helps a lot when it comes to resolving issues.

**Comment by galehouse5** [comment]
Duplicate of #17.
