### ISSUE TITLE
Autodraw "still draws" when removed from Chrome

### ISSUE THREAD

**Issue by ted-valdez2000** [galehouse5/skribbl-io-autodraw#22]
It all started when I was playing with my friend on Discord. I have push to talk enabled and (don't ask this, my push button is on my mouse, it went back a page. I'm going to reconfigure this button). 

I dragged an image (it was a corndog) to skribbl.io, suddenly when I released my button it went back a page, and it made my mouse go crazy. My cursor was flipping out to the edges of my monitor. I removed the extension and my cursor flips out occasionally, even on bootup. I uninstalled my mouse drivers and it did not do the trick. 

_Now this is not a good place to ask how to fix this issue, but how could I fix this?_

**Comment by josephAttia** [comment]
This might be late but do you still have the same issue

**Comment by ted-valdez2000** [comment]
I'm also late but not anymore. I solved my issue by buying a completely new mouse
