### ISSUE TITLE
[QUESTION] Why is it so slow?

### ISSUE THREAD

**Issue by ShinyStardust** [galehouse5/skribbl-io-autodraw#30]
I've been using the extension for the past week now, and most of the images I choose for it to draw, it never finishes in time. nor does it finish it halfway. The images aren't that high in quality either, so I don't get what's the problem. Is there any way I could make it faster?

**Comment by galehouse5** [comment]
Duplicate of #21.

**Comment by galehouse5** [comment]
Duplicate of #21
