### ISSUE TITLE
Fix gray extension icon

### ISSUE THREAD

**Issue by GlitchMasta47** [galehouse5/skribbl-io-autodraw#4]
- [x] Find out why the icon is gray
- [ ] Make a pull request to colorize the icon if on *.skribbl.io

**Comment by GlitchMasta47** [comment]
Found fix - PR coming when I test and confirm it works.

**Comment by galehouse5** [comment]
Great! Thanks for your help.

**Comment by galehouse5** [comment]
The icon seems to colorize properly on latest Chrome. No code change needed now.
