### ISSUE TITLE
having trouble installing

### ISSUE THREAD

**Issue by OMEGALUL54** [galehouse5/skribbl-io-autodraw#5]
when i try to load unpacked it says that it cant manifest it or something

**Comment by galehouse5** [comment]
Are you still having issues? Please post a screenshot.

**Comment by GlitchMasta47** [comment]
It's been 5 months. @galehouse5 go ahead and close this, they haven't paid attention to their email.

**Comment by GlitchMasta47** [comment]
For us to help you better, tell me exactly what step you get stuck on following the guide I posted on https://github.com/galehouse5/skribbl-io-autodraw/issues/2#issuecomment-414463698

**Comment by galehouse5** [comment]
Thanks @GlitchMasta47.

This is easier now, just [download from Chrome Web Store](https://chrome.google.com/webstore/detail/autodraw-for-skribblio/bpnefockcbbpkbahgkkacjmebfheacjb).
