### ISSUE TITLE
Drawing is now only black*

### ISSUE THREAD

**Issue by 46009361** [galehouse5/skribbl-io-autodraw#56]
Did skribbl.io patch it again so the script can't change the colours anymore? It seems like this happened at the same time as the update where the avatar of the person now shows below "(name) is choosing a word!"

*or whatever colour it was before the image gets dragged and dropped

**Comment by Throwawayaccountguy** [comment]
Yep, the bot wont choose colours. whats going on? thanks

**Comment by 46009361** [comment]
@catches lol your drawing doesn't match the word at all

**Comment by 46009361** [comment]
Maybe a solution would be to simulate key presses right when the drawing starts.

**Comment by 46009361** [comment]
Update: It seems to work again. Seems like skribbl.io reverted the update back to a previous version of the game.

**Comment by 46009361** [comment]
Actually, it turns out that, apparently, 951707d fixed a small change to the UI. I knew that the game did this, but I didn't bother changing the status at the time because I thought it wasn't relevant and I forgot my thought process now that led up to that point lol.
