### ISSUE TITLE
Colors are bad

### ISSUE THREAD

**Issue by gellyfisher** [galehouse5/skribbl-io-autodraw#7]
Green doesn't ever get drawn. Probably some bug in the color distance. I took some code from online and put it together to get a good color distance. see gellyfisher patch 1 branch

**Comment by FreePvp** [comment]
blue is never drawn either

**Comment by galehouse5** [comment]
Thanks, @gellyfisher. I'm having trouble reproducing green not drawing. Can you attach an image that demonstrates the problem?

I'll draw this color gradient in skribbl.io:
![image](https://user-images.githubusercontent.com/1687988/56935243-cb149e00-6abd-11e9-9a0b-de3dc7785590.png)

Here is the existing color distance function:
![image](https://user-images.githubusercontent.com/1687988/56935205-a1f40d80-6abd-11e9-9238-954ba5bbcd85.png)

Here is the color distance function you propose:
![image](https://user-images.githubusercontent.com/1687988/56935282-feefc380-6abd-11e9-9a0b-c9142503d79d.png)

I'm happy to change the color distance function to improve accuracy. I'm having trouble deciding whether the proposed function is an improvement though. Can you help convince me?

**Comment by galehouse5** [comment]
@FreePvp, can you attach an image that demonstrates blue not drawing when it should?

**Comment by FreePvp** [comment]
Also seems like lots of pink, but idk, heres a sans image vs what it draws:

![no blue](https://user-images.githubusercontent.com/11426776/56936226-35304180-6ac4-11e9-9b29-c86281064247.PNG)
No blue eye

**Comment by gellyfisher** [comment]
Yeah that and I get this orange instead of green if I use your code (I changed the drawing order though so that it's less messy)
<img width="672" alt="yours" src="https://user-images.githubusercontent.com/19496494/56949387-12894180-6b33-11e9-9130-ce099a3a71ad.PNG">
while if I use my code (https://github.com/gellyfisher/skribbl-io-autodraw/blob/master/color-helper.js) then I get 
<img width="681" alt="mine" src="https://user-images.githubusercontent.com/19496494/56949412-216ff400-6b33-11e9-991f-54d794cd1bd5.PNG">

**Comment by galehouse5** [comment]
Thanks! I'll investigate further.

**Comment by FreePvp** [comment]
> Yeah that and I get this orange instead of green if I use your code (I changed the drawing order though so that it's less messy)
> <img alt="yours" width="672" src="https://user-images.githubusercontent.com/19496494/56949387-12894180-6b33-11e9-9130-ce099a3a71ad.PNG">
> while if I use my code (https://github.com/gellyfisher/skribbl-io-autodraw/blob/master/color-helper.js) then I get
> <img alt="mine" width="681" src="https://user-images.githubusercontent.com/19496494/56949412-216ff400-6b33-11e9-991f-54d794cd1bd5.PNG">

I tried out your code and get more detailed images, still missing blues. 
![no blue detailed](https://user-images.githubusercontent.com/11426776/56995815-c9f07900-6b70-11e9-81f9-7b01b36f3078.PNG)

**Comment by gellyfisher** [comment]
Its not perfectly blue either in the original. Maybe theres just not a color that's close to its eye color? Maybe try to use something more colorful for testing

**Comment by galehouse5** [comment]
Using [CIEDE2000](https://en.wikipedia.org/wiki/Color_difference#CIEDE2000) now:

![image](https://user-images.githubusercontent.com/1687988/59727753-f9347580-9204-11e9-8f1c-df528e691c87.png)

![image](https://user-images.githubusercontent.com/1687988/59727755-fb96cf80-9204-11e9-853a-3b3ddd3a172e.png)

Light shades of blue resolve to light gray:

![image](https://user-images.githubusercontent.com/1687988/59727757-fd609300-9204-11e9-8dab-b9fdb799b4bd.png)

Not perfect.

**Comment by TheAlienDrew** [comment]
My bug probably relates to the missing colors thing in this bug https://github.com/galehouse5/skribbl-io-autodraw/issues/12
